In [1]:
# Importing python library
from sklearn.neighbors import NearestNeighbors
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')
import numpy as np
import seaborn as sns

In [3]:
# Read in csv file to each playlist and graph each attribute to spot differences. 
# I am reading in my happy and euphonious playlists.

mixed = pd.read_csv("rdataset7.csv")

# plt.plot(mixed.energy, color='blue')
# plt.plot(mixed.valence, color='red')
# mixed['danceability']=mixed['danceability'].astype(int)
mixed.isnull().values.any()
mixed.dtypes



danceability        float64
energy              float64
acousticness        float64
instrumentalness    float64
valence             float64
target                int64
dtype: object

In [4]:
# STEP 6: Normalize/Standardize the dataset

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(mixed.drop('target', axis=1))
scaled_features = scaler.transform(mixed.drop('target',axis=1))
scaled_features
mixed_feat = pd.DataFrame(scaled_features, columns = mixed.columns[:-1])
mixed_feat.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   danceability      160 non-null    float64
 1   energy            160 non-null    float64
 2   acousticness      160 non-null    float64
 3   instrumentalness  160 non-null    float64
 4   valence           160 non-null    float64
dtypes: float64(5)
memory usage: 6.4 KB


In [14]:
# STEP 7: Split dataset into training and testing sets
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
X = mixed_feat
y = mixed['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=30, shuffle=True)
forest = RandomForestClassifier(n_estimators=100, max_depth= 5)
forest.fit(X_train, y_train)

RandomForestClassifier(max_depth=5)

In [12]:
forest.score(X_test, y_test)

0.8125

In [13]:
pred = forest.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[ 4  0  3  0]
 [ 0 10  1  0]
 [ 0  0  2  0]
 [ 0  0  2 10]]
              precision    recall  f1-score   support

           0       1.00      0.57      0.73         7
           1       1.00      0.91      0.95        11
           2       0.25      1.00      0.40         2
           3       1.00      0.83      0.91        12

    accuracy                           0.81        32
   macro avg       0.81      0.83      0.75        32
weighted avg       0.95      0.81      0.85        32

